name: networkd
description: A native Dart client library to access systemd-networkd.
repository: https://github.com/d-loose/networkd.dart
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

platforms:
  linux:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dbus: ^0.7.8
  meta: ^1.8.0
  mocktail: ^0.3.0
