name: networkd
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.exampl0.1om

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dbus: ^0.7.8
  meta: ^1.8.0
