name: networkd
description: A native Dart client library to access the systemd-networkd DBus API.
repository: https://github.com/canonical/networkd.dart
issue_tracker: https://github.com/canonical/networkd.dart/issues
version: 0.1.1

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  linux:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mocktail: ^0.3.0

dependencies:
  dbus: ^0.7.8
  meta: ^1.8.0
